service: mega_blog
image: kodeon6/kojo/mega_blog
servers:
  - 37.27.36.63
registry:
  username: mega_blog.imlikeu.com
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY